spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/leasesoftv2
    username: root
    password: rootpass
  jpa:
    hibernate.ddl-auto: validate
    generate-ddl: true
    show-sql: true
